# =========================================
# render.yaml — configuração automática Render
# =========================================
services:
  - type: web
    name: sistema-pedidos
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pedidos-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6

databases:
  - name: pedidos-db
    plan: free
    databaseName: pedidos_db_ihvt
    user: pedidos_db_ihvt_user
